{{- if .Values.postgresql.enabled -}}
{{- $fullName := include "taiga.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  labels:
{{ include "taiga.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  taiga-db-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  taiga-db-username: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  taiga-db-database: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  taiga-db-hostname: "{{ .Release.Name  }}-postgresql"
{{- end }}
